services:
  dcs-postgres:
    image: postgres:17-alpine
    container_name: dcs-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dcs-pgadmin
    restart: always
    depends_on:
      - dcs-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: root@email.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 8081:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
volumes:
  pgadmin-data:
  postgres-data:
    